pipeline {
    agent {
        docker {
            image 'python:3.10'
            args '-v /var/run/docker.sock:/var/run/docker.sock'
        }
    }
    stages {
        stage('Setup') {
            steps {
                sh 'python --version'
                sh 'python -m venv venv'
                sh '. venv/bin/activate && pip install --upgrade pip'
                sh '. venv/bin/activate && pip install -r messaging_app/requirements.txt'
            }
        }
        stage('Tests') {
            steps {
                sh '. venv/bin/activate && pytest'
            }
        }
    }
}
